<?php
$pdo = new PDO('mysql:host=sql304.ezyro.com;dbname=ezyro_40355109_misc','ezyro_40355109', '9k4djnc0');
// See the "errors" folder for details...
// See the "errors" folder for details...
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);